name: §d默认风格
Boss血条:
  default:
    是否开启: true
    间隔时间: 5
    是否根据玩家血量变化: false
    显示颜色: RED
    消息轮播:
      - '§e[系统] §a欢迎来到本服务器{换行}{换行}§e[系统]§7 游玩时请遵循服务器的规章制度           '
      - '§e[系统] §a欢迎来到本服务器{换行}{换行}§e[系统]§7 未成年玩家请注意游戏时长 掌控好游玩时间'
      - '§e[系统] §a欢迎来到本服务器{换行}{换行}§e[系统]§7 拒绝盗版游戏 享受健康生活              '
头部:
  default:
    是否开启: true
    显示: '{vip} §2✤§r {ch} §2✤§6 {name}§2  {ms}\n§2❤§b {h}/{mh}'
聊天:
  default:
    是否开启: true
    显示: "§7[§e{levelName}§7] §7[§a{ms}§7] §b{name} §7>> §r{msg}"
    是否仅在世界内有效: false
底部:
  default:
    是否开启: false
    显示类型: 0
    显示: ""
聊天栏公告:
  default:
    是否开启: false
    间隔时间: 30
    消息轮播:
      - '§7[ 公告 ]§a 欢迎大家来到本服务器'
      - '§7[ 公告 ]§e 当前在线玩家 {online} / {maxplayer}'
计分板:
  default:
    是否开启: true
    Title: '§7--§e◎{color} {name}信息栏 §e◎§7--'
    Line:
      - ''
      - '§e◎§f世界:  §a {levelName}'
      - '§e◎§f位置:  §e {x},{y},{z}'
      - '  '
      - '§e◎§f金币:  §a {money}'
      - '§e◎§f手持:  §b {id}:{damage}'
      - '    '
      - '§e◎§f人数:  §7 {online} / {maxplayer}'
      - '§e◎§f延迟:  §a {ms}'
      - '     '
      - '§7--§e◎§2==>> ~*..*~§2<<==§e◎§7--'
